//getting the actionType 

//login action
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_REQUEST_SUCCESS = 'LOAD_PROFILE_SUCCESS';
export const LOGIN_REQUEST_FAILURE = 'INSERT_PROFILE_FAILURE';


//EventFormAction actin
export const EVENTFORM_REQUEST = 'EVENTFORM_REQUEST';
export const EVENTFORM_REQUEST_SUCCESS = 'EVENTFORM_REQUEST_SUCCESS';
export const EVENTFORM_REQUEST_FAILURE = 'EVENTFORM_REQUEST_FAILURE';


//fetch event list action
export const FETCH_EVENTLIST_REQUEST = "FETCH_EVENTLIST_REQUEST";
export const FETCH_EVENTLIST_REQUEST_SUCCESS = "FETCH_EVENTLIST_REQUEST_SUCCESS";
export const FETCH_EVENTLIST_REQUEST_FAILURE = "FETCH_EVENTLIST_REQUEST_FAILURE";


//Delete button action
export const DELETEBTN_REQUEST = 'DELETEBTN_REQUEST';
export const DELETEBTN_REQUEST_SUCCESS = 'DELETEBTN_REQUEST_SUCCESS';
export const DELETEBTN_REQUEST_FAILURE = 'DELETEBTN_REQUEST_FAILURE'


//EventDetail action
export const EVENTDETAIL_REQUEST = 'EVENTDETAIL_REQUEST';
export const EVENTDETAIL_REQUEST_SUCCESS = 'EVENTDETAIL_REQUEST_SUCCESS';
export const EVENTDETAIL_REQUEST_FAILURE = 'EVENTDETAIL_REQUEST_FAILURE';


//DetailButton action
export const DETAILBTN_REQUEST = 'DETAILBTN_REQUEST';
export const DETAILBTN_REQUEST_SUCCESS = 'DETAILBTN_REQUEST_SUCCESS';
export const DETAILBTN_REQUEST_FAILURE = 'DETAILBTN_REQUEST_FAILURE'
//create poll action
// export const CREATE_POLL_REQUEST = 'CREATE_POLL_REQUEST';
// export const CREATE_POLL_SUCCESS = 'CREATE_POLL_SUCCESS';
// export const CREATE_POLL_FAILURE = 'CREATE_POLL_FAILURE';

// //load poll actions
// export const LOAD_POLLS_REQUEST = 'LOAD_POLLS_REQUEST';
// export const LOAD_POLLS_FAILURE = 'LOAD_POLLS_FAILURE';
// export const LOAD_POLLS_SUCCESS = 'LOAD_POLLS_SUCCESS';

// //load single poll 
// export const LOAD_POLL = 'LOAD_POLL';
// export const LOAD_POLL_SUCCESS = 'LOAD_POLL_SUCCESS';
// export const LOAD_POLL_FAILURE = 'LOAD_POLL_FAILURE';

// //remove poll action
// export const REMOVE_POLL_REQUEST = 'REMOVE_POLL_REQUEST';
// export const REMOVE_POLL_SUCCESS = 'REMOVE_POLL_SUCCESS';
// export const REMOVE_POLL_FAILURE = 'REMOVE_POLL_FAILURE';

// //Close modal 
// export const CLOSE_MODAL_SUCCESS = 'CLOSE_MODAL_SUCCESS';

// //submit option 
// export const SUBMIT_VOTE_SUCCESS = 'SUBMIT_VOTE_SUCCESS';

// //add poll to Ui actions 
// export const ADD_POLL_UI = "ADD_POLL_UI";
// export const ADD_POLL_UI_SUCCESS = "ADD_POLL_UI_SUCCESS";
// export const ADD_POLL_UI_FAILURE = "ADD_POLL_UI_FAILURE";